// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANyS5oP2igjLwxtQtMXQYXM_PUlX7Mgy0',
    appId: '1:437660843680:web:691cccf75adeb445f513c5',
    messagingSenderId: '437660843680',
    projectId: 'annapurna-92ffd',
    authDomain: 'annapurna-92ffd-b90fd.firebaseapp.com',
    storageBucket: 'annapurna-92ffd.appspot.com',
    measurementId: 'G-S1EQQB4QYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76cgAFaFGvlcjpxI7TjoEJDrraIUaK3I',
    appId: '1:437660843680:android:41c0cc445e9191c3f513c5',
    messagingSenderId: '437660843680',
    projectId: 'annapurna-92ffd',
    storageBucket: 'annapurna-92ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHXDiK3L7Frla_LSJk2SJI-GOaogVmkT0',
    appId: '1:437660843680:ios:032a8117151b459ff513c5',
    messagingSenderId: '437660843680',
    projectId: 'annapurna-92ffd',
    storageBucket: 'annapurna-92ffd.appspot.com',
    iosBundleId: 'com.example.ledgerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHXDiK3L7Frla_LSJk2SJI-GOaogVmkT0',
    appId: '1:437660843680:ios:3e674ef522e81bdaf513c5',
    messagingSenderId: '437660843680',
    projectId: 'annapurna-92ffd',
    storageBucket: 'annapurna-92ffd.appspot.com',
    iosBundleId: 'com.example.ledgerapp.RunnerTests',
  );
}
